* STARTED Brownian Tree builder
This is a common lisp program to visualize Brownian Trees and Random Walk trails with a lot of variable parameters available to make the resulting more interesting.
Look at brownian-tree.org and brownian-trails.org files for more details on the implementation.
The Image creation part of the program is written as a separate SVG module, whose capabilities are limited to the requirements of the current project.

Few sample brownian-tree images.
[[file:trails-1200x900-600dot450-10.svgz][Trails Sample Image]]

** TODO Features
Few sample brownian-trails images.
look at trails-*-svgz images in root folder. gzipped svg image has a lot of variables so it might load the cpu up.


Bugs:
+ [todo] some thing weird going on with path background.
+ [fixed after using format with ~{ ~} directives] path initialize-instance must not be that nightmare. need to make it more streamlined, or break it into fewer parts if memory insufficient. It might be better to used advanced pretty printing of format.
